// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > types/database.types.ts
//
// For now, here's a placeholder type structure based on our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      lessons: {
        Row: {
          id: string;
          level: number;
          title: string;
          description: string | null;
          category: string | null;
          order_index: number;
          estimated_duration: number | null;
          is_published: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          level: number;
          title: string;
          description?: string | null;
          category?: string | null;
          order_index: number;
          estimated_duration?: number | null;
          is_published?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          level?: number;
          title?: string;
          description?: string | null;
          category?: string | null;
          order_index?: number;
          estimated_duration?: number | null;
          is_published?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      vocabulary: {
        Row: {
          id: string;
          lesson_id: string | null;
          italian: string;
          english: string;
          pronunciation: string | null;
          audio_url: string | null;
          type: string | null;
          gender: string | null;
          example_sentence_italian: string | null;
          example_sentence_english: string | null;
          difficulty_level: number;
          order_index: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          lesson_id?: string | null;
          italian: string;
          english: string;
          pronunciation?: string | null;
          audio_url?: string | null;
          type?: string | null;
          gender?: string | null;
          example_sentence_italian?: string | null;
          example_sentence_english?: string | null;
          difficulty_level?: number;
          order_index?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          lesson_id?: string | null;
          italian?: string;
          english?: string;
          pronunciation?: string | null;
          audio_url?: string | null;
          type?: string | null;
          gender?: string | null;
          example_sentence_italian?: string | null;
          example_sentence_english?: string | null;
          difficulty_level?: number;
          order_index?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_progress: {
        Row: {
          id: string;
          user_id: string;
          lesson_id: string;
          completed: boolean;
          score: number;
          attempts: number;
          last_attempt_at: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          lesson_id: string;
          completed?: boolean;
          score?: number;
          attempts?: number;
          last_attempt_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          lesson_id?: string;
          completed?: boolean;
          score?: number;
          attempts?: number;
          last_attempt_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      vocabulary_mastery: {
        Row: {
          id: string;
          user_id: string;
          vocabulary_id: string;
          mastery_level: number;
          correct_count: number;
          incorrect_count: number;
          last_reviewed_at: string | null;
          next_review_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          vocabulary_id: string;
          mastery_level?: number;
          correct_count?: number;
          incorrect_count?: number;
          last_reviewed_at?: string | null;
          next_review_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          vocabulary_id?: string;
          mastery_level?: number;
          correct_count?: number;
          incorrect_count?: number;
          last_reviewed_at?: string | null;
          next_review_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      achievements: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          icon_name: string | null;
          requirement_type: string | null;
          requirement_value: number | null;
          points: number;
          badge_tier: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          icon_name?: string | null;
          requirement_type?: string | null;
          requirement_value?: number | null;
          points?: number;
          badge_tier?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          icon_name?: string | null;
          requirement_type?: string | null;
          requirement_value?: number | null;
          points?: number;
          badge_tier?: string | null;
          created_at?: string;
        };
      };
      user_achievements: {
        Row: {
          id: string;
          user_id: string;
          achievement_id: string;
          earned_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          achievement_id: string;
          earned_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          achievement_id?: string;
          earned_at?: string;
        };
      };
      user_streaks: {
        Row: {
          user_id: string;
          current_streak: number;
          longest_streak: number;
          last_activity_date: string | null;
          total_study_days: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          current_streak?: number;
          longest_streak?: number;
          last_activity_date?: string | null;
          total_study_days?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          current_streak?: number;
          longest_streak?: number;
          last_activity_date?: string | null;
          total_study_days?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_stats: {
        Row: {
          user_id: string;
          total_lessons_completed: number;
          total_words_learned: number;
          total_study_time_minutes: number;
          average_score: number;
          pronunciation_accuracy: number;
          total_points: number;
          level: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          total_lessons_completed?: number;
          total_words_learned?: number;
          total_study_time_minutes?: number;
          average_score?: number;
          pronunciation_accuracy?: number;
          total_points?: number;
          level?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          total_lessons_completed?: number;
          total_words_learned?: number;
          total_study_time_minutes?: number;
          average_score?: number;
          pronunciation_accuracy?: number;
          total_points?: number;
          level?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_preferences: {
        Row: {
          user_id: string;
          daily_goal_minutes: number;
          notification_enabled: boolean;
          audio_enabled: boolean;
          pronunciation_practice_enabled: boolean;
          ui_language: string;
          theme: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          daily_goal_minutes?: number;
          notification_enabled?: boolean;
          audio_enabled?: boolean;
          pronunciation_practice_enabled?: boolean;
          ui_language?: string;
          theme?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          daily_goal_minutes?: number;
          notification_enabled?: boolean;
          audio_enabled?: boolean;
          pronunciation_practice_enabled?: boolean;
          ui_language?: string;
          theme?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
